### ISSUE TITLE
UNDERCOVER: error while covering /path/to/webpaste.el

### ISSUE THREAD

**Issue by etu** [undercover-el/undercover.el#42] opened 2018-08-14 18:07 UTC
I'm using undercover since before in https://github.com/etu/webpaste.el, but I've noticed that coveralls stopped getting updated.

And when I run `env COVERALLS_REPO_TOKEN=<redacted-token> cask exec buttercup -L . tests/unit/` I get the following log:

```
Loading /home/etu/code/webpaste.el/tests/load-undercover.el (source)...
UNDERCOVER: error while covering /home/etu/code/webpaste.el/webpaste.el
UNDERCOVER: please open a new issue at https://github.com/sviridov/undercover.el/issues
Loading /home/etu/code/webpaste.el/tests/load-undercover.el (source)...
Loading /home/etu/code/webpaste.el/tests/load-undercover.el (source)...
Loading /home/etu/code/webpaste.el/tests/load-undercover.el (source)...
Loading /home/etu/code/webpaste.el/tests/load-undercover.el (source)...
Loading /home/etu/code/webpaste.el/tests/load-undercover.el (source)...
Loading /home/etu/code/webpaste.el/tests/load-undercover.el (source)...
Loading /home/etu/code/webpaste.el/tests/load-undercover.el (source)...
Loading /home/etu/code/webpaste.el/tests/load-undercover.el (source)...
Running 19 out of 21 specs.

Default post field lambda
  can add language and text as post data
  can paste raw pastes

Create lambdas to use on failures, 
  with fallback
  without fallback

Get provider priority
  can autopopulate provider priority if it's not predefined
  can fetch static population of provider priority

Don't to paste region or buffer because of wrong answer to question
  can't paste because of answer to question is no

Paste region or buffer because of correct answer to question
  can paste because of answer to question is yes

Paste region and buffer without question being asked
  can paste entire buffers or regions

Paste text to provider
  can paste text to provider and try second provider if called again

Run provider lambda to paste text

Creation of providers
  can trigger the error lambda of a provider
  can trigger the success lambda of a provider
  can failover from a broken provider  

Returning URLs to the user
  can put in kill-ring and message the user
  can open an external browser with the url
  can append language on return
  can run user defined hooks

Create lambdas to use on successes
  using a response header
  when using some request.el response thingy  
  when returning a string with an url

The feature
  can use bug and feature

Ran 19 out of 21 specs, 0 failed, in 1.0 seconds.
UNDERCOVER: No coverage information. Make sure that your files are not compiled
```

And, I'm sure that my file isn't compiled.

**Comment by sviridov** [comment] 2018-08-27 08:08
Hi @etu, sorry for the long response, I was offline all these days.

Please, see this comment: https://github.com/sviridov/undercover.el/issues/40#issuecomment-399855951. It describes how to find the reason for this error.

**Comment by etu** [comment] 2018-08-27 16:38
This seems to fail for me:
https://github.com/etu/webpaste.el/blob/master/webpaste.el#L221-L224

If I remove the `&rest` from the function it will start doing reports -- but then some of my tests will fail. So I don't know what to do about that :confused:

**Comment by etu** [comment] 2018-08-27 16:56
One workaround would be to to name the rest like `&rest rest` or so, but I put the `&rest` there because things may send arguments to the function that doesn't matter in that case.

**Comment by sviridov** [comment] 2018-08-30 11:19
Does this `&rest` keyword actually do anything or is it only for documentation purposes? If it's only for documentation maybe you can just move it to comments or docstring? Otherwise, maybe there is a way to disable the warning for this particular line? 

Edebug spec clearly defines that `&rest` keyword should be followed by the variable name.

```
(([&rest arg]
  [&optional
   ["&optional" cl-&optional-arg &rest cl-&optional-arg]]
  [&optional
   ["&rest" arg]]
  [&optional
   ["&key"
    [cl-&key-arg &rest cl-&key-arg]
    &optional "&allow-other-keys"]]
  [&optional
   ["&aux" &rest &or
    (symbolp &optional def-form)
    symbolp]]))
```

**Comment by etu** [comment] 2018-08-30 12:13
It does things that is crucial for the function to work.

For example this:
```elisp
(cl-defun foobar-test (&rest)
  (message "foobar-test-executed"))

(foobar-test 1 2 3)
```

The function doesn't complain if it get's unexpected arguments, if `&rest` is removed it will complain because it encounters a lisp-error `wrong-number-of-arguments`.

And if I put `&rest foobar` there, I will get a warning because the variable is unused.

The thing is that the function is sent in as a callback to another place that will always send an argument. But in this callback's case it doesn't need the input. So I use `&rest` to not make it fail by `wrong-number-of-arguments` but to discard the variable without causing any warnings.

Maybe there's some other param then `&rest` that I could use...

**Comment by etu** [comment] 2018-09-09 16:55
@sviridov The function is sent as a closure to another function. And sometimes it must send an argument to a supplied function, and sometimes it doesn't need this. Do you know if there's any way to see if a function accepts arguments or not?

I haven't had time to look into this but it's the only solution I see to resolve this without major re-architecture work.

**Comment by sviridov** [comment] 2018-09-09 17:52
@etu well, if coverage information for this function is not that valuable you can rewrite it in a way that edebug will ignore. I use it in `undercover` internally. See example here: https://github.com/sviridov/undercover.el/blob/master/undercover.el#L138.

**Comment by CyberShadow** [comment] 2019-11-22 21:24
Hi @etu,

I managed to reproduce the problem and find a workaround.

The following patch in `webpaste.el` resolves the issue for me:

```patch
diff --git a/webpaste.el b/webpaste.el
index 375ca2e..2dfb174 100644
--- a/webpaste.el
+++ b/webpaste.el
@@ -205,7 +205,7 @@ precalculated, and also available both for pre and post request access.")
                  (webpaste--paste-text text))))
 
 
-(cl-defun webpaste--providers-error-lambda-no-failover (&rest)
+(cl-defun webpaste--providers-error-lambda-no-failover (&rest _)
   "Predefined error callback for providers that shouldn't do failover."
   (cl-function (lambda (&key error-thrown &allow-other-keys)
                  (message "Got error: %S" error-thrown))))
```

It looks like `edebug` is having some trouble with handling unnamed `&rest` arguments.

I also opened https://github.com/undercover-el/undercover.el/pull/52 to improve the error message that undercover.el prints.

As this is a problem with `edebug` and not due to a defect in any code in this repository, I am going to close this issue. Thanks!

**Closed by CyberShadow** 2019-11-22 21:24 UTC

**Comment by etu** [comment] 2019-11-23 07:26
@CyberShadow Oh wow, big thanks!

I had forgotten about this issue but have now applied the patch and it seems to work very well :)
