### ISSUE TITLE
Can't require subr-x on Travis

### ISSUE THREAD

**Issue by Wilfred** [undercover-el/undercover.el#35] opened 2017-10-05 23:39 UTC
I have a build that failing on Travis: https://travis-ci.org/Wilfred/suggest.el/builds/283954800 which is using [this tiny code](https://github.com/Wilfred/suggest.el/blob/fix_travis/suggest.el).

The code only does this:

```
(require 'subr-x)

(defun foo (x)
  x)

(provide 'suggest)
```

However, Travis dies with:

```
cask exec ert-runner
UNDERCOVER: error while covering /home/travis/build/Wilfred/suggest.el/suggest.el
UNDERCOVER: please open a new issue at https://github.com/sviridov/undercover.el/issues
Cannot open load file: subr-x
UNDERCOVER: No coverage information. Make sure that your files are not compiled?
```

I can't reproduce this locally:

```
$ UNDERCOVER_FORCE=true cask exec ert-runner
.

Ran 1 test in 0.000 seconds

Sending: report to coveralls.io
Sending: OK
```

Any idea what's wrong?

**Comment by sviridov** [comment] 2017-10-09 18:45
Hi @Wilfred, sorry for the late response.

To be honest I have no idea why that happens. I tried to emulate Travis environment with

```
TRAVIS=true EMACS=`evm bin emacs-24.5-travis` cask exec ert-runner
```

But test runs successfully for me. Have you tried exactly same environment without `undercover.el`? Does it work fine without it?

**Comment by CyberShadow** [comment] 2019-11-22 20:52
Hi @Wilfred,

I wanted to have a look at this, but could not reproduce the problem.

I forked https://github.com/CyberShadow/suggest.el to my GitHub account, enabled it in Travis CI, then triggered a manual build on the `fix_travis` branch. However, the Travis build [succeeds](https://travis-ci.org/CyberShadow/suggest.el/builds/615745621). So, I'm guessing whatever the problem was, it was fixed due to a change in Travis CI or undercover.el.

As this issue is quite old and I don't see a way to get to a reproducible test case from here right now,  I'm going to close this; but, if you do still have a way to reproduce this problem, please leave a comment and we can reopen and look into it. Thanks!

**Closed by CyberShadow** 2019-11-22 20:52 UTC
